LOCAL_DIR := $(GET_LOCAL_DIR)
TARGET := m5c
MODULES += app/mt_boot \
           dev/lcm
MTK_EMMC_SUPPORT = yes
DEFINES += MTK_NEW_COMBO_EMMC_SUPPORT
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_PUMP_EXPRESS_SUPPORT := yes
MTK_LCM_PHYSICAL_ROTATION = 0
CUSTOM_LK_LCM="jd9365_dsi_vdo_holitech_hd720"
#DEFINES += MTK_LCM_DEVICE_TREE_SUPPORT
MTK_SECURITY_SW_SUPPORT = no
MTK_VERIFIED_BOOT_SUPPORT = no
MTK_SEC_FASTBOOT_UNLOCK_SUPPORT = no
DEBUG := 5
BOOT_LOGO:=qhd
#DEFINES += WITH_DEBUG_DCC=1
DEFINES += WITH_DEBUG_UART=1
#DEFINES += WITH_DEBUG_FBCON=1
#DEFINES += MACH_FPGA=y
#DEFINES += MACH_FPGA_NO_DISPLAY=y
DEFINES += MTK_GPT_SCHEME_SUPPORT
MTK_EFUSE_DOWNGRADE = no
MTK_GOOGLE_TRUSTY_SUPPORT = no
MTK_DM_VERITY_OFF = yes
MTK_DYNAMIC_CCB_BUFFER_GEAR_ID =
